### ISSUE TITLE
Cannot construct instance of `nl.obren.sokrates.sourcecode.core.FoundTag`

### ISSUE THREAD

**Issue by MAHDTech** [zeljkoobrenovic/sokrates#32] opened 2022-05-29 06:02 UTC
Hi, 

thank you so much for creating Sokrates, a very useful tool to get some insight into project source code.

I'm attempting to create a Landscape of 50+ reports and one particular report is failing with an error causing the landscape to fail.

Removing this one repo will successfully run the landscape so I have narrowed it down to just one failed report.

I have two questions;

1. Is there a way to ignore an individual report when building a landscape so the entire process doesn't fail (and the report which has the error is just excluded)

2. Any pointers where I might start to narrow down the cause?

- The error is as follows;

```bash
[main] ERROR nl.obren.sokrates.common.io.JsonMapper - com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `nl.obren.sokrates.sourcecode.core.FoundTag` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (StringReader); line: 587, column: 5] (through reference chain: nl.obren.sokrates.sourcecode.analysis.results.CodeAnalysisResults["foundTags"]->java.util.ArrayList[0])
Exception in thread "main" java.lang.IllegalArgumentException: Cannot construct instance of `nl.obren.sokrates.sourcecode.core.FoundTag` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator) (line 587, column 5)
        at nl.obren.sokrates.common.io.JsonMapper.getObject(JsonMapper.java:30)
        at nl.obren.sokrates.sourcecode.landscape.analysis.LandscapeAnalyzer.getProjectAnalysisResults(LandscapeAnalyzer.java:167)
        at nl.obren.sokrates.sourcecode.landscape.analysis.LandscapeAnalyzer.getProjectAnalysisResults(LandscapeAnalyzer.java:153)
        at nl.obren.sokrates.sourcecode.landscape.analysis.LandscapeAnalyzer.lambda$analyze$2(LandscapeAnalyzer.java:47)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at nl.obren.sokrates.sourcecode.landscape.analysis.LandscapeAnalyzer.analyze(LandscapeAnalyzer.java:45)
        at nl.obren.sokrates.reports.landscape.statichtml.LandscapeAnalysisCommands.generateReport(LandscapeAnalysisCommands.java:65)
        at nl.obren.sokrates.reports.landscape.statichtml.LandscapeAnalysisCommands.update(LandscapeAnalysisCommands.java:41)
        at nl.obren.sokrates.cli.CommandLineInterface.updateLandscape(CommandLineInterface.java:266)
        at nl.obren.sokrates.cli.CommandLineInterface.run(CommandLineInterface.java:103)
        at nl.obren.sokrates.cli.CommandLineInterface.main(CommandLineInterface.java:74)
```

- A full gist of all the commands I executed and their output is also available at this link

https://gist.github.com/MAHDTech/36da7b5ca0f371cf5ec3dbde1a9d01be

**Comment by zeljkoobrenovic** [comment] 2022-05-29 07:56
Hi,

Thanks for spotting this problem, your info was sufficient to identify the cause. The issues should be fixed now, you can download the latest version of source code or binary. Let me know if the error repeats.

I will also look at making the analysis more robust by ignoring failed individual projects (with perhaps an error log to see which projects have been ignored).

**Closed by zeljkoobrenovic** 2022-05-29 07:56 UTC

**Comment by MAHDTech** [comment] 2022-05-29 15:23
Works great, thank you!
